# Generated by Django 3.2.7 on 2021-09-25 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClassApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='djangoclasses',
            old_name='Duration',
            new_name='duration',
        ),
    ]
